### ISSUE TITLE
SDXL1.0，No such file or directory: __init__.py

### ISSUE THREAD

**Issue by shiyk92** [fitCorder/fcSuite#1]
Traceback (most recent call last):
  File "I:\Stable-Diffusion-Comfyui\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'I:\\Stable-Diffusion-Comfyui\\ComfyUI\\custom_nodes\\fcSuite\\__init__.py'

Cannot import I:\Stable-Diffusion-Comfyui\ComfyUI\custom_nodes\fcSuite module for custom nodes: [Errno 2] No such file or directory: 'I:\\Stable-Diffusion-Comfyui\\ComfyUI\\custom_nodes\\fcSuite\\__init__.py'

Import times for custom nodes:
   0.0 seconds: I:\Stable-Diffusion-Comfyui\ComfyUI\custom_nodes\fcSuite.py
   0.0 seconds (IMPORT FAILED): I:\Stable-Diffusion-Comfyui\ComfyUI\custom_nodes\fcSuite

**Comment by Lestat1986** [comment]
Same issue for me. Cloned it to "custom_nodes" folder with git and got the exact same error.

**Comment by fitCorder** [comment]
The path should be "ComfyUI\custom_nodes\fcSuite.py"

**Comment by Y3418** [comment]
![Image](https://github.com/user-attachments/assets/695ef320-5387-46c5-ab65-5b3a2b3c4845)
还是会报错
