### ISSUE TITLE
<title>fcSuite/fcSuite.py at main · fitCorder/fcSuite · GitHub</title>

### ISSUE THREAD

**Issue by cullenbohannon** [fitCorder/fcSuite#2]
Followed the instructions and copied the fcSuite.py file into the custom_nodes folder (root)
I get the following error in the console after starting comfyUI:

```
Traceback (most recent call last):
  File "[redacted]\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "[redacted]\ComfyUI\custom_nodes\fcSuite.py", line 90
    <title>fcSuite/fcSuite.py at main · fitCorder/fcSuite · GitHub</title>
                                      ^
SyntaxError: invalid character '·' (U+00B7)

Cannot import [redacted]\ComfyUI\custom_nodes\fcSuite.py module for custom nodes: invalid character '·' (U+00B7) (fcSuite.py, line 90)
```

**Comment by cullenbohannon** [comment]
There is an issue downloading the .py file from GitHub - had to do the 'Raw' export and save and it worked.
